trigger:
- azure-pipelines

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildProjects: ''

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.x'
  inputs:
    version: 6.x
    
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: CmdLine@2
  displayName: 'Identify Changed Solutions'
  inputs:
    script: |
      changed_projects=$(git diff-tree --name-only --no-commit-id HEAD HEAD~1 | grep .csproj | awk -F/ '{print $1}')
      echo "##vso[task.setvariable variable=buildProjects]$changed_projects"
      name: identify_changed_projects

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build API(s)'
  inputs:
    command: 'build'
    projects: '$(buildProjects)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish API(s)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'